# React Storybook — port 6006
server {
    listen      6006;
    root        /usr/share/nginx/storybook;
    index       index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# Vue Storybook — port 6007
server {
    listen      6007;
    root        /usr/share/nginx/storybook-vue;
    index       index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# Svelte Storybook — port 6008
server {
    listen      6008;
    root        /usr/share/nginx/storybook-svelte;
    index       index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# Angular Storybook — port 6009
server {
    listen      6009;
    root        /usr/share/nginx/storybook-angular;
    index       index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
